### PR TITLE
Davis l webb/user interface

### PR DESCRIPTION
**Pull request by DavisLWebb**

### CODE REVIEW

**Comment by kirbyk** [comment]
Before we merge this in, can you make all the links bootstrap buttons, and make all the tables bootstrap as well?

**Comment by DavisLWebb** [comment]
I thought I got them all but iIl double check then push again

**Comment by DavisLWebb** [comment]
I added buttons to the courses page.  Are there anymore pages? I have worked on the homepage (welcome#index), the signup page, the login page, and courses.

**Comment by DavisLWebb** [comment]
I updated what I believe to be all of the pages.

**Comment by kirbyk** [comment]
LGTM :+1:

**Comment by DavisLWebb** [comment]
Sweet.  That means bootstrap for sprint 1 should be complete.

**Pull request merged**
